### ISSUE TITLE
Cert package -- request test for serialization of example data

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#332] opened 2019-02-10 02:52 UTC
May a test please be added to show what the `exampleData` looks like after it has been flattened?

**Comment by xpepermint** [comment] 2019-02-11 11:58
Hum ... flattening happens in a loop and the result is an array of recipes. Here's an example:

```ts
{
  "name": "John",
  "book": {
    "title": "0xcert Framework"
  }
}
```
```ts
[
  {
    "path": []
    // root level data { name, book }
  },
  {
    "path": ["book"],
    // book levl data { title }
  }
]
```

**Comment by xpepermint** [comment] 2019-02-11 12:11
I'm not sure how to expose only part of the functionality of a protected method `buildSchemaProps`. It's much easier to explain the concept. Closing this issue, since the mechanism is covered by other tests.

**Comment by fulldecent** [comment] 2019-02-11 19:31
Could I please see a full, non-trivial example. I'm trying to break this stuff, and want to look under the hood!

**Comment by xpepermint** [comment] 2019-02-11 19:38
That good! I'd also wanna break it but the problem is that there is no single flattened JSON. There are multiple objects. Here's the magic: https://github.com/0xcert/framework/blob/master/packages/0xcert-cert/src/core/cert.ts#L111

**Comment by xpepermint** [comment] 2019-02-11 20:12
Here are the steps that [buildSchemaProps](https://github.com/0xcert/framework/blob/master/packages/0xcert-cert/src/core/cert.ts#L111) creates for [exampleSchema/exampleData](https://github.com/0xcert/framework/blob/master/packages/0xcert-cert/src/tests/core/helpers/schema.ts):
```
value: {
  "path": [
    "books",
    0,
    "note"
  ],
  "value": "A0",
  "key": "books.0.note",
  "group": "books.0"
}
value: {
  "path": [
    "books",
    0,
    "title"
  ],
  "value": "B0",
  "key": "books.0.title",
  "group": "books.0"
}
object: [
  {
    "path": [
      "books",
      0,
      "note"
    ],
    "value": "A0",
    "key": "books.0.note",
    "group": "books.0"
  },
  {
    "path": [
      "books",
      0,
      "title"
    ],
    "value": "B0",
    "key": "books.0.title",
    "group": "books.0"
  }
]
value: {
  "path": [
    "books",
    1,
    "note"
  ],
  "value": "A1",
  "key": "books.1.note",
  "group": "books.1"
}
value: {
  "path": [
    "books",
    1,
    "title"
  ],
  "value": "B1",
  "key": "books.1.title",
  "group": "books.1"
}
object: [
  {
    "path": [
      "books",
      1,
      "note"
    ],
    "value": "A1",
    "key": "books.1.note",
    "group": "books.1"
  },
  {
    "path": [
      "books",
      1,
      "title"
    ],
    "value": "B1",
    "key": "books.1.title",
    "group": "books.1"
  }
]
array: [
  {
    "path": [
      "books",
      0,
      "note"
    ],
    "value": "A0",
    "key": "books.0.note",
    "group": "books.0"
  },
  {
    "path": [
      "books",
      0,
      "title"
    ],
    "value": "B0",
    "key": "books.0.title",
    "group": "books.0"
  },
  {
    "path": [
      "books",
      1,
      "note"
    ],
    "value": "A1",
    "key": "books.1.note",
    "group": "books.1"
  },
  {
    "path": [
      "books",
      1,
      "title"
    ],
    "value": "B1",
    "key": "books.1.title",
    "group": "books.1"
  }
]
value: {
  "path": [
    "email"
  ],
  "value": "A",
  "key": "email",
  "group": ""
}
value: {
  "path": [
    "event",
    "organizer",
    "email"
  ],
  "value": "A",
  "key": "event.organizer.email",
  "group": "event.organizer"
}
value: {
  "path": [
    "event",
    "organizer",
    "name"
  ],
  "value": "B",
  "key": "event.organizer.name",
  "group": "event.organizer"
}
object: [
  {
    "path": [
      "event",
      "organizer",
      "email"
    ],
    "value": "A",
    "key": "event.organizer.email",
    "group": "event.organizer"
  },
  {
    "path": [
      "event",
      "organizer",
      "name"
    ],
    "value": "B",
    "key": "event.organizer.name",
    "group": "event.organizer"
  }
]
value: {
  "path": [
    "event",
    "title"
  ],
  "value": "A",
  "key": "event.title",
  "group": "event"
}
object: [
  {
    "path": [
      "event",
      "organizer",
      "email"
    ],
    "value": "A",
    "key": "event.organizer.email",
    "group": "event.organizer"
  },
  {
    "path": [
      "event",
      "organizer",
      "name"
    ],
    "value": "B",
    "key": "event.organizer.name",
    "group": "event.organizer"
  },
  {
    "path": [
      "event",
      "title"
    ],
    "value": "A",
    "key": "event.title",
    "group": "event"
  }
]
value: {
  "path": [
    "name"
  ],
  "value": "B",
  "key": "name",
  "group": ""
}
value: {
  "path": [
    "tags",
    0
  ],
  "value": 1,
  "key": "tags.0",
  "group": "tags"
}
value: {
  "path": [
    "tags",
    1
  ],
  "value": 2,
  "key": "tags.1",
  "group": "tags"
}
array: [
  {
    "path": [
      "tags",
      0
    ],
    "value": 1,
    "key": "tags.0",
    "group": "tags"
  },
  {
    "path": [
      "tags",
      1
    ],
    "value": 2,
    "key": "tags.1",
    "group": "tags"
  }
]
object: [
  {
    "path": [
      "books",
      0,
      "note"
    ],
    "value": "A0",
    "key": "books.0.note",
    "group": "books.0"
  },
  {
    "path": [
      "books",
      0,
      "title"
    ],
    "value": "B0",
    "key": "books.0.title",
    "group": "books.0"
  },
  {
    "path": [
      "books",
      1,
      "note"
    ],
    "value": "A1",
    "key": "books.1.note",
    "group": "books.1"
  },
  {
    "path": [
      "books",
      1,
      "title"
    ],
    "value": "B1",
    "key": "books.1.title",
    "group": "books.1"
  },
  {
    "path": [
      "email"
    ],
    "value": "A",
    "key": "email",
    "group": ""
  },
  {
    "path": [
      "event",
      "organizer",
      "email"
    ],
    "value": "A",
    "key": "event.organizer.email",
    "group": "event.organizer"
  },
  {
    "path": [
      "event",
      "organizer",
      "name"
    ],
    "value": "B",
    "key": "event.organizer.name",
    "group": "event.organizer"
  },
  {
    "path": [
      "event",
      "title"
    ],
    "value": "A",
    "key": "event.title",
    "group": "event"
  },
  {
    "path": [
      "name"
    ],
    "value": "B",
    "key": "name",
    "group": ""
  },
  {
    "path": [
      "tags",
      0
    ],
    "value": 1,
    "key": "tags.0",
    "group": "tags"
  },
  {
    "path": [
      "tags",
      1
    ],
    "value": 2,
    "key": "tags.1",
    "group": "tags"
  }
]
```

**Comment by xpepermint** [comment] 2019-02-24 16:53
@fulldecent Based on NY meeting, I've prepared https://github.com/0xcert/framework-cert-test and include certification nonces https://github.com/0xcert/framework/issues/378.

**Closed by xpepermint** 2019-02-24 16:53 UTC
Labels: enhancement
